SELECT ConsultaTodosAcolhidosEntidade.NomeAcolhido, ConsultaTodosAcolhidosEntidade.DataDesacolhimento
FROM ConsultaTodosAcolhidosEntidade
WHERE (((ConsultaTodosAcolhidosEntidade.DataDesacolhimento) Is Null));
